// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo1Ce8CIbe0zoM-atGf1UjqrWNskQDbgY',
    appId: '1:306225543145:web:d79f2552dcebb1c1a47d78',
    messagingSenderId: '306225543145',
    projectId: 'bmw-flutter-20782',
    authDomain: 'bmw-flutter-20782.firebaseapp.com',
    storageBucket: 'bmw-flutter-20782.appspot.com',
    measurementId: 'G-2CKJVP7HP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8PS6lyPE74LK6G7rgx3kRE-vDWK1xRM4',
    appId: '1:306225543145:android:94c14fbe908713aea47d78',
    messagingSenderId: '306225543145',
    projectId: 'bmw-flutter-20782',
    storageBucket: 'bmw-flutter-20782.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuMFtu_KtZ-Qd3xaad7y7CF6PCjX-ebUo',
    appId: '1:306225543145:ios:b48888b25c113daca47d78',
    messagingSenderId: '306225543145',
    projectId: 'bmw-flutter-20782',
    storageBucket: 'bmw-flutter-20782.appspot.com',
    iosClientId:
        '306225543145-9mfcd8u3b1e81e27hu9p5ujjl7ecuspu.apps.googleusercontent.com',
    iosBundleId: 'lk.nidarshana.bmw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuMFtu_KtZ-Qd3xaad7y7CF6PCjX-ebUo',
    appId: '1:306225543145:ios:718405fef498ec7aa47d78',
    messagingSenderId: '306225543145',
    projectId: 'bmw-flutter-20782',
    storageBucket: 'bmw-flutter-20782.appspot.com',
    iosClientId:
        '306225543145-dlnh0k7jbvhcbl06320gddml9d6alfpb.apps.googleusercontent.com',
    iosBundleId: 'lk.nidarshana.bmw.RunnerTests',
  );
}
